### ISSUE TITLE
Never works on Beta 14.1

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/recaptcha#13]
Beta 14, reCpatcha 0.2.0

Invislble ReCaptcha
Error console.

```
Uncaught TypeError: this.recaptcha.execute is not a function
    exports index.js:37
    e extend.js:61
    handleEvent render.js:888
    I render.js:910
    T render.js:735
    l render.js:730
    l render.js:122
    l render.js:63
    u render.js:50
    l render.js:134
    l render.js:63
    u render.js:50
    l render.js:134
    l render.js:63
    l render.js:162
    l render.js:66
    f render.js:423
    h render.js:302
    f render.js:477
    f render.js:416
    f render.js:488
    f render.js:419
    f render.js:488
    f render.js:419
    h render.js:302
    exports render.js:964
    a mount-redraw.js:14
    show ModalManagerState.js:35
    onclick HeaderSecondary.js:77
    handleEvent render.js:888
    I render.js:910
    T render.js:735
    l render.js:730
    l render.js:122
    l render.js:63
    l render.js:162
    l render.js:66
    u render.js:50
    l render.js:134
    l render.js:63
    u render.js:50
    l render.js:134
    l render.js:63
    l render.js:162
    l render.js:66
    u render.js:50
    h render.js:277
    exports render.js:964
    mount mount-redraw.js:45
    mount ForumApplication.js:128
    boot Application.js:176
    <anonymous> (index):160

```

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/99158614-df86ae80-26d4-11eb-8b11-d5d3051eab89.jpg)

![SharedScreenshot 1](https://user-images.githubusercontent.com/5006150/99158619-f6c59c00-26d4-11eb-9b9d-97d593f04982.jpg)

**Comment by PeopleInside** [comment]
Issue is present also with checkbox. Users are unable to register.

**Comment by bluisier** [comment]
Yep I have the same issue with both checkbox and invisible recapcha on Beta 14.1. If I disable the extension, everything works fine

**Comment by Magicalex** [comment]
Same issue on my side

**Comment by EvilExecutor** [comment]
Hopefully, these problems will be fixed with the new release (will be tagged soon). Feel free to re-open the issue persists!

**Comment by PeopleInside** [comment]
Thanks for fixing this
